language: go
sudo: false

go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - mkdir -p $GOPATH/gopkg.in/fgrosse
  - mv $(pwd) $GOPATH/gopkg.in/fgrosse/goldi.v1

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
  - go get -v -t gopkg.in/fgrosse/goldi.v1/...

script:
  - go test -cover -coverpkg gopkg.in/fgrosse/goldi.v1            -coverprofile goldi.coverprofile      .
  - go test -cover -coverpkg gopkg.in/fgrosse/goldi.v1/goldigen   -coverprofile goldigen.coverprofile   ./goldigen
  - go test -cover -coverpkg gopkg.in/fgrosse/goldi.v1/validation -coverprofile validation.coverprofile ./validation

after_success:
  - gover
  - goveralls -coverprofile=gover.coverprofile -repotoken $COVERALLS_TOKEN
